---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Deploy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Deploy main site vhost
  template:
    src: sites-available/megakuponi.conf.j2
    dest: /etc/nginx/sites-available/megakuponi
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/megakuponi
    dest: /etc/nginx/sites-enabled/megakuponi
    state: link
  notify: reload nginx

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Enable and start nginx
  systemd:
    name: nginx
    enabled: true
    state: started
