restic_repo: "{{ restic_repo_base }}/test"

nginx_active_domains:
  - megacupones.com.bo
  - lasantadelahorro.com

nginx_disabled_domains: []

nginx_admin_domain: lasantadelahorro.com
nginx_ssl_cert_domain: megacupones.com.bo
